name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com/
          scope: '@zwkang-dev'

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: pnpm i

      # Release with semantic-release
      - name: Release
        run: npx release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}